# Generated by Django 6.1.1 on 2026-10-07 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDeviceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='account.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_mappings', to='account.acdevice')),
            ],
            options={
                'db_table': 'customer_device_mappings',
                'constraints': [models.UniqueConstraint(fields=('customer', 'device'), name='unique_customer_device_mapping')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSiteMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='account.customer')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_mappings', to='account.site')),
            ],
            options={
                'db_table': 'customer_site_mappings',
                'constraints': [models.UniqueConstraint(fields=('customer', 'site'), name='unique_customer_site_mapping')],
            },
        ),
        migrations.CreateModel(
            name='SiteDeviceMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_mappings', to='account.acdevice')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_mappings', to='account.site')),
            ],
            options={
                'db_table': 'site_device_mappings',
                'constraints': [models.UniqueConstraint(fields=('site', 'device'), name='unique_site_device_mapping')],
            },
        ),
    ]
