# Generated by Django 6.1.1 on 2026-10-02 06:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_city_user_division_user_region_user_taluka'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ac_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='OFF', max_length=20)),
                ('capacity_ton', models.FloatField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_ac_devices', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ac_devices', to='account.site')),
            ],
            options={
                'db_table': 'ac_devices',
                'ordering': ['ac_id'],
            },
        ),
    ]
