# Generated by Django 6.1.1 on 2026-10-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_branch_latitude_branch_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
