# Generated by Django 6.1.1 on 2026-10-02 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_acdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Dashboard', max_length=255)),
                ('main_filters', models.JSONField(blank=True, default=dict)),
                ('card_filters', models.JSONField(blank=True, default=dict)),
                ('visible_widgets', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to='account.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_preferences',
                'ordering': ['-is_default', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_dashboard_name_per_user')],
            },
        ),
    ]
