# Generated by Django 6.1.1 on 2026-10-09 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_branch_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='account.branch'),
        ),
    ]
