# Generated by Django 6.1.1 on 2026-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_acdevice_tpt_device_id_acdevice_tpt_sync_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acdevice',
            name='tpt_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tpt_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='tpt_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tpt_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
